import LocalizedStrings from 'react-native-localization';

export default TextStrings = new LocalizedStrings({
  en: {
    //auth
    email: 'Email',
    enterEmail: 'Enter Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    enterConfirmPassword: 'Enter Confirm Password',
    enterPassword: 'Enter Password',
    fpassword: 'Forgot Password?',
    login: 'Login',
    dontHave: "Don't have an account?",
    register: 'Register',
    signup: 'Sign up',
    firstName: 'First Name',
    enterFirstName: 'Enter First Name',
    lastName: 'Last Name',
    enterLastName: 'Enter Last Name',
    selectDataofBirth: 'Select Data of Birth',
    alreadyhaveanaccount: 'Already have an account?',
    premium: 'Premium',
    freeTrial: 'Free Trial',
    bySigningupyouagree: 'By Signing up you agree to ',
    termsConditions: 'Terms & Conditions',
    and: 'and',
    privacypolicy: 'Privacy policy.',
    phonenumber: 'Phone number',
    enterPhonenumber: 'Enter Phone Number',
    CPasswordMsg: 'Password and confirm password should be same.',
    selectSubscriptionType: 'Select subscription type',
    regError: 'Register Error',
    emailVerification: 'Email Verification',
    WehavesentyoutheOTPon: 'We have sent you the OTP on',
    pleasecheckyourmail: 'please check your mail.',
    Didntyougetthecode: 'Didn t you get the code?',
    resendAgain: 'RESEND AGAIN',
    submit: 'Submit',
    cancel: 'Cancel',
    otpMsg: 'OTP is required field',
    otp6digt: 'OTP should be 6 digit',
    verifyCodeError: 'Verify Code Error',
    otpSendError: 'Otp Send Error',
    userRegisteredSuccessfully: 'user registered successfully',
    OtpResend: 'OTP code resend successfully',
    changePassword: 'Change Password',
    privacyPolicy: 'Privacy policy',
    termsAndConditions: 'Terms and conditions',
    cookiePolicy: 'Cookie policy',
    settings: 'Settings',
    logout: 'Logout',
    update: 'Update',
    updatePassword: 'Update password',
    newPassword: 'New Password',
    updatedPasswordMsg: 'Your password has been updated successfully!',
    forgotPasswordDesc:
      'Don t worry it happens, Please enter details associated with your account',
    goBackto: 'Go back to',
    forgetPasswordError: 'Forget Password Error',
    resetPassword: 'Reset password',
    Setnewpassword: 'Set new password',

    //Alert
    emailMsg: 'Email is required field',
    emailInvalidMsg: 'Please enter valid email address',
    passwordMsg: 'Password is required field',
    Minimum8characters: 'The password should be at least Minimum 8 characters',
    passwordformate: 'a letter, a number and a symbol',
    alertPassAllowedSpecialChar:
      'Symbols allowed @,$,!,%,*,#,?,& (No other symbol allowed)',
    emailNotVerified: 'Email not verified',
    loginError: 'Login Error',
  },
  it: {},
  fr: {
    how: 'Comment voulez-vous votre œuf aujourd hui ?',
    lang: 'French',
  },
  es: {
    how: "'¿Cómo quieres tu huevo hoy?'",
    lang: 'Spanish',
  },
  de: {
    how: 'Wie möchtest du dein Ei heute?',
    lang: 'German',
  },
});
